pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {
        stage('Git Clone') {
            steps {
                echo 'Récupération du code source...'
                checkout([$class: 'GitSCM',
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: 'https://github.com/SaadBengrich/tp30.git']]
                ])
            }
        }

        stage('Build') {
            steps {
                echo 'Construction du projet...'
                dir('jenkins/POV-JAVA') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Exécution des tests...'
                dir('jenkins/POV-JAVA') {
                    bat 'mvn test'
                }
            }
            post {
                always {
                    junit 'jenkins/POV-JAVA/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Create Docker Image') {
            steps {
                echo 'Construction de l\'image Docker...'
                dir('jenkins/POV-JAVA') {
                    bat 'docker build -t lachgar/pos .'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Déploiement de l\'application...'
                bat '''
                    docker stop test-pos || exit 0
                    docker rm test-pos || exit 0
                    docker run -d --name test-pos -p 8585:8282 lachgar/pos
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline exécuté avec succès!'
        }
        failure {
            echo 'Le pipeline a échoué!'
        }
    }
}
