pipeline {
    agent any
    tools {
        maven 'maven'
    }

    stages {
        stage('Git Clone') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: 'main']],
                        userRemoteConfigs: [[url: 'https://github.com/SaadBengrich/tp30.git']]
                    ])
                }
            }
        }

        stage('Build') {
            steps {
                script {
                   // Se placer dans le dossier du projet avant de lancer Maven
                   dir('jenkins/POV-JAVA') {
                      sh 'mvn clean install'
                   }
                }
            }
        }

        stage('Create Docker Image') {
            steps {
                script {
                    dir('jenkins/POV-JAVA') {
                        sh 'docker build -t lachgar/pos .'
                    }
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    dir('jenkins/POV-JAVA') {
                        sh "docker run --name test-pos -d -p 8585:8282 lachgar/pos"
                    }
                }
            }
        }
    }
}
